spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_HOST:localhost:3306}/${RDS_DATABASE:fitu}
    username: ${RDS_USERNAME:root}
    password: ${RDS_PASSWORD:root}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY} 
      s3:
        bucket: amzn-s3-fitu-bucket
      region:
        static: ap-northeast-2 
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 350MB

springdoc:
  swagger-ui:
    doc-expansion: none

s3:
  path:
    temp: temp/
    body-image: bodyImage/
infra:
  ai:
    api:
      body-image: http://13.125.144.217:8000
      recommendation:
        base-url: http://13.125.144.217:8002/vision/recommendation
  weather:
    api:
      service-key: ${WEATHER_API_KEY}
  geocoding:
    api:
      service-key: ${GEOCODING_API_KEY}   

team3:
  aws: 
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
      temp-bucket: ${AWS_S3_TEMP_BUCKET_NAME}
    region: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
ai:
  model:
    base-url: ${AI_MODEL_BASE_URL}
